The `include` macro includes the contents of another card in a card.

NOTE: As Cyberismo cards have a title, metadata fields, and links in addition to the AsciiDoc contents, we need to include more than just the AsciiDoc document. Therefore, Cyberismo does not support https://docs.asciidoctor.org/asciidoc/latest/directives/include/[the native AsciiDoc include directive]. 

== Parameters

The `include` macro supports the following parameters:

* `"cardKey"` : The key of the card to include
* `"levelOffset"`: An optional offset to adjust the heading levels of the included content. Should be a number as string, such as `"+1"`, `"+2"` or `"-1"`.
* `"title"`: Optional parameter. Whether to include the title of the card in the included content. The value must be `"include"` to include the title, `"exclude"` to exclude the title, or `"only"` to include the title only and exclude all other content. If the parameter is omitted, then the title will be included 
* `"pageTitles"`: Optional, either `"normal"` or `"discrete"` to control whether page titles will be included as discrete headings or normal headings. If this parameter is omitted, then normal headings will be included. See https://docs.asciidoctor.org/asciidoc/latest/blocks/discrete-headings/[AsciiDoc documentation] for more information

== Example

For example, consider the following macro:

```
{{#raw}}

{{#include}}
  "cardKey": "docs_i13qzif0"
{{/include}}

{{/raw}}
```

This macro includes the contents of {{#xref}}"cardKey": "docs_i13qzif0"{{/xref}} in the card, as follows:

{{#include}}
  "cardKey": "docs_i13qzif0"
{{/include}}
