== Introduction

A workflow defines the states and state transitions that cards move through during their lifecycle.

For example, a task workflow could consist of the states and transitions *Open* → *In Progress* → *Done*, and a document workflow could be defined as *Draft* → *Approved* → *Archived*.

== Managing workflows using the Cyberismo command-line tool

To see a list of the available workflows, use the following command:

  $ cyberismo show workflows

The names of workflows are of the format `_module_/workflows/_workflow_`, for example `base/workflows/decision`.

To see the help for how to create a workflow, use the following command:

  $ cyberismo create workflow --help

To create a new workflow, for example `myWorkflow`, use the following command:

  $ cyberismo create workflow myWorkflow

Cyberismo will create a new file called `myWorkflow.json` in `.cards/local/workflows/myWorkflow.json`. If the card prefix of your Cyberismo project is `example`, then the full name of the new workflow will be `example/workflows/myWorkflow`.

When choosing a name for your workflow, see xref:docs_8.adoc[Naming conventions].

To finalise the workflow definition, you need to edit the `myWorkflow.json` file with a text editor.

== Workflow file format

Workflows are defined in JSON files that follow the https://github.com/CyberismoCom/cyberismo/blob/main/tools/schema/workflowSchema.json[workflow schema], as described in the following tables.

=== Basic structure of a workflow definition

.The properties of a workflow
|===
|Property|Type|Description|Required

|**name**
|`string`
|The name of this workflow
| &#10003; Yes

|**states**
|`object` `[]`
|The states of the workflow, see below.
| &#10003; Yes

|**transitions**
|`object` `[]`
|The state transitions of the workflow, see below.
| &#10003; Yes

|===

Additional properties are not allowed.

=== Workflow states

The `states` property of a workflow is an array of objects that have the following properties:

.Properties of the items in the states array
|===
|Property|Type|Description|Required

|**name**
|`string`
|A string that identifies the workflow state.
| &#10003; Yes

|**category**
|`string`
|One of the following values: "initial", "active", or "closed". The category of the workflow state is used for visualising the state of the card on broad terms.
| &#10003; Yes

|===

=== Workflow transitions

The `transitions` property of a workflow is an array of objects that have the following properties:

* `name`: A name that identifies the workflow transition. Required.
* `fromState`: An array of state names from which this transition can start. Each item of the array is a name of the starting state of the transition. The wildcard '*' denotes any state, and an empty value denotes the transition to create a new card with this workflow. Required.
* `toState`: A string that is the name of the end state of the transition. Required.

.Properties of the items in the transitions array
|===
|Property|Type|Description|Required

|**name**
|`string`
|A string that identifies the workflow transition.
| &#10003; Yes

|**fromState**
|`string []`
|An array of state names from which this transition can start. Each item of the array is a name of the starting state of the transition. The wildcard '*' denotes any state, and an empty string denotes the transition to create a new card with this workflow.
| &#10003; Yes

|**toState**
|`string`
|A string that is the name of the end state of the transition.
| &#10003; Yes

|===

== Mapping to a logic program

Workflows are mapped to logic program facts using the following function terms:
{{#report}}
    "name": "base/reports/predicates",
    "category": "Workflow",
    "orderBy": "rank"
{{/report}}