== Recommended method for Linux

On Linux, the easiest way to try Cyberismo is likely by using a container platform such as xref:docs_w0puey08.adoc[Docker] or xref:docs_il74geqj.adoc[Podman].
 
== Building and running Cyberismo locally from source

=== Prerequisites

Install Git. While Cyberismo does not directly depend on Git, you will need it to manage Cyberismo content, such as when installing Cyberismo modules. Git installation guide: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

Install Node.js. The currently supported Node.js version is the latest LTS, v20.10.0. Node.js is downloadable from https://nodejs.org/.

*Ubuntu 20.04* and newer support automatic dependency installation via a post-install script. The post-install script will download a working clingo binary into the project directory and verify the presence of graphviz, which must be installed manually if it is not already present. Graphviz can be installed with the following command:

  $ sudo apt-get update && sudo apt-get install -y graphviz

*Other Linux distributions*: Automatic dependency installation is currently a work in progress. In the meantime, follow these steps to manually install the required dependencies:

. The currently supported Clingo version is 5.7.1. We recommend installing a Python-enabled build using Anaconda, following the instructions provided at: https://github.com/potassco/clingo/releases/.

. Install the latest version of https://clingraph.readthedocs.io/en/latest/clingraph/installation.html[Clingraph].

=== Building

Take the following steps:

. Clone the source repository:

  $ git clone https://github.com/CyberismoCom/cyberismo.git
  
. Change to the source directory. If you have already cloned the repository earlier, remember to pull the latest changes:

  $ cd cyberismo
  $ git pull origin main # Optional

. Install pnpm with npm command:

  $ npm install -g pnpm
  
. Execute the following commands:

  $ pnpm setup
  $ pnpm install
  $ pnpm build
  $ pnpm link -g

=== Running

After building and installing, run `cyberismo --help` to see the command line help.