== Docker image from Docker Hub

For macOS and Linux, this is probably the easiest way to try out Cyberismo. For Windows, building the application locally from source is the recommended way, and it is not half as frightening as it sounds.

=== Prerequisites

Install Git. While Cyberismo does not directly depend on Git, you will need it to manage Cyberismo content, such as when installing Cyberismo modules. Git installation guide: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

The system must have Docker or a similar container environment installed, capable of running Linux-based images. The simplest way to install a container environment is to install https://www.docker.com[Docker Desktop].

=== Downloading image from Docker Hub
The latest image can be downloaded with the following command:

  $ docker pull cyberismo/cyberismo

=== Running

*Linux & macOS*

To simplify running the image, you can use the following alias:

  $ alias cyberismo='docker run --init --rm -it --user $(id -u):$(id -g) -e HOME=/tmp -v $(pwd):/project:Z -p 3000:3000 cyberismo/cyberismo:latest cyberismo'

.Explanation of alias
[%collapsible]
====
The alias command allows you to execute the configured Docker environment with a single, simple command.

Flags in command:

* --init flag ensures proper signal handling and zombie process reaping in the container.
* -rm: Removes the container automatically after it exits.
* -it: Runs the container in interactive mode.
* --user: Container user will use the same user id as the user executing the command. This will prevent file ownership problems.
* -e HOME=/some/path sets the HOME environment variable so tools like Antora can write to user-specific directories without permission errors.
* -v: Maps the current execution directory to the /project directory inside the container, sharing files between host and container.
* to support *Security-Enhanced Linux (SELinux)*, the volume mount includes the :Z option and uses an absolute path to the present working directory (`-v $(pwd):/project:Z`) 
* -p: Forwards the port from the container to the host machine, enabling access to the hosted web service.
====

Afterward, you can run the application using the following command:

  $ cyberismo --help

*Windows*

The Windows environment does not support aliases like Linux and macOS do, so the command to use Docker is:

  $ docker run --rm -it --user $(id -u):$(id -g) -v .:/project -p 3000:3000 cyberismo/cyberismo cyberismo --help



