:sectnums:
This tutorial shows how to create a new Cyberismo project with the base module.

Prerequisites: xref:docs_13.adoc[Install Cyberismo].

== Create a project

First, let's check the command line help for creating a project by executing the following command:

[source,console]
----
$ cyberismo create project --help
Usage: cyberismo create project [options] <name> <prefix> <path>

Create a project

Arguments:
  name        Name for project.
              Name can contain letters (a-z|A-Z), spaces, underscores or hyphens.
  prefix      Prefix that will be part of each card's card key. Prefix can be 3-10 characters (A-Z)
  path        Path where project is created.
              Note that folder is automatically created.

Options:
  -h, --help  display help for command
----

Create a new project called "Cyberismo tutorial" that has the card key prefix tutorial in the directory `cyberismo-tutorial` with the following command:

[source,console]
----
$ cyberismo create project "Cyberismo tutorial" tutorial cyberismo-tutorial
----

== Import the base module to your new project

When you create a new project, Cyberismo will prompt you whether you want to import some of the available content modules from the Cyberismo module hub.

Select the *Base module*.

Cyberismo will then fetch the base module from GitHub and import it to your new project.

== Create a page

The base module includes a page template. To create the first card in the new project, execute the following command:

[source,console]
----
$ cd cyberismo-tutorial
$ cyberismo create card base/templates/page
----

== Start the Cyberismo app

You can view and edit the new project and its first card with the Cyberismo app. To start the app, execute the following command:

[source,console]
----
$ cyberismo app
----

Then open a browser and navigate to http://localhost:3000/.