== Introduction

To test our application, we provide a simple demo environment for you to explore. The demo environment includes a welcome page that helps you navigate the project contents, as well as an example secure development project for an imaginary IoT device.

This demo project showcases the capabilities of our application, including:

- automatic process metrics
- interconnected tasks
- an exceptional threat modeling tool
- and much more

You can learn more about these features on the welcome page, go ahead and give it a try!

== How to test the demo

To try out our Cyberismo application, we offer two simple methods:

* Demo Docker Image: https://hub.docker.com/repository/docker/cyberismo/cyberismo-demo
* Demo Git Project: https://github.com/CyberismoCom/cyberismo-demo

Further instructions are provided below.

=== Docker image demo environment

* Verify that you have Docker installed by running the command:

  $ docker --version

If you don’t see a version number, you may need to install Docker or use the other demo option.

* Use the following command to start the environment (the image will download on the first run):

  $ docker run --rm -it -p 3000:3000 cyberismo/cyberismo-demo

Once running, the demo environment is accessible in your browser at:
http://localhost:3000

* To update the demo environment to the latest image, run:

  $ docker pull cyberismo/cyberismo-demo:latest

=== Demo project in a local Cyberismo application

* If you haven’t already installed Cyberismo, follow the installation instructions in link:/cards/docs_17[Installing Cyberismo] under **Building and Running Cyberismo from Source**.
   
* Download the demo project using the following command:

  $ git pull https://github.com/CyberismoCom/cyberismo-demo.git

* Navigate to the downloaded directory and run:

  $ cyberismo app

Once running, the demo environment is accessible in your browser at:
http://localhost:3000






















