== Building and running Cyberismo locally from source

=== Prerequisites

Install Git. While Cyberismo does not directly depend on Git, you will need it to manage Cyberismo content, such as when installing Cyberismo modules. Git can be downloaded from https://git-scm.com/downloads/win

Install Node.js. The currently supported Node.js version is the latest LTS, v22.14.0. Node.js is downloadable from https://nodejs.org/.

When building Cyberismo on Windows, the system automatically installs the required dependencies (Clingo and libraries) using a prebuilt package by Cyberismo.

=== Building

Take the following steps:

. Clone the source repository:

  $ git clone https://github.com/CyberismoCom/cyberismo.git

. Change to the source directory. If you have already cloned the repository earlier, remember to pull the latest changes:

  $ cd cyberismo
  $ git pull origin main # Optional

. Install pnpm with npm command:

  $ npm install -g pnpm

. Execute the following commands:

  $ pnpm setup
  $ pnpm install
  $ pnpm build
  $ pnpm link -g


=== Running

After building and installing, run `cyberismo --help` to see the command line help.