This page describes the naming conventions in the Cyberismo solution.

== Module names

Modules are named in so called kebab-case. By convention, the source code repository of a module should begin with `module-`, for example `module-example`.

== Names of card types, workflows, field types, link types

Card types, workflows, field types, link types and other basic concepts of the Cyberismo content format are named in kebab-case.

When we refer to these concepts in the configuration, the references always include the module name and the type of the concept, for example `my-module/templates/decision`

Do not include the type of the item in the name. For example, if you need a workflow for decisions, it should be called `decision` rather than `decision-workflow`. It will be referred to as `module-name/workflows/decision`.

The following table shows how the main Cyberismo concepts are referred to in Cyberismo modules.

.Naming of Cyberismo concepts
[%autowidth]
|===
|Concept  |Example Name

|Workflow
|`module1/workflows/example`
|Card type
|`module1/cardtypes/example`
|Field type
|`module1/fieldtypes/example`
|Link type
|`module1/linktypes/example`
|Template
|`module1/templates/example`
|===

== File names

Various files in the Cyberismo content format should be named in kebab-case. 
This includes several JSON files that have the file extension `.json`, and logic program file names that have the file extension `.lp`. For example, `security-issue.json` and `risk-level-calculation.lp`.

== Naming in logic programs

We follow the standard Answer Set Programming naming conventions when naming the atoms, constants and variables. The names of atoms and constants begin with a lowercase character, and variable names begin with an uppercase character.  If a symbol includes multiple words, then an underscore character '_' is used as a separator.

== Names of Cyberismo concepts in `field` predicates

Some Cyberismo concepts are used in `field` predicates of generated logic programs. In these cases, the names are given in `camelCase`, which is the naming convention in Cyberismo's implementation language TypeScript. These names are listed in the following table.

.Cyberismo concepts in `field` predicates
[%autowidth]
|===
|Concept  |Name in `field` predicates

|Card type
|`cardtype`
|Title
|`title`
|Workflow state
|`workflowState`

|===
