This page describes the naming conventions in the Cyberismo solution. These naming conventions are relevant when designing new content modules.

== General principle: use camelCase

In general, all the user-configurable names use the so called `camelCase` notation. 

Modules have a separately configurable name, which is defined in the `cardsConfig.json` file by convention in `camelCase`. Similarly by convention, the source code repository of a module is named in kebab-case and it should begin with `module-`, for example `module-my-example`.

Other types of Cyberismo configuration do not have separately configurable names, but their name is the file or directory name in which they are declared. Card types, workflows, field types, link types and other basic concepts of the Cyberismo content format are named in `camelCase`. For example, a `securityIssue` card type would be defined in a JSON file `securityIssue.json`

All other types of files in the Cyberismo content format should also be named in `camelCase`. This includes logic program file names that have the file extension `.lp`, such as `riskLevelCalculation.lp`.

When we refer to these concepts in the configuration, the references always include the module name and the type of the concept, for example `myModule/templates/decision`

Do not include the type of the item in the name. For example, if you need a workflow for decisions, it should be called `decision` rather than `decisionWorkflow`. It will be referred to as `moduleName/workflows/decision`.

The following table shows how the main Cyberismo concepts are referred to in Cyberismo modules.

.Naming of Cyberismo concepts
[%autowidth]
|===
|Concept  |Example Name

|Workflow
|`module1/workflows/example`
|Card type
|`module1/cardTypes/example`
|Field type
|`module1/fieldTypes/example`
|Link type
|`module1/linkTypes/example`
|Template
|`module1/templates/example`
|===

== Naming in logic programs

We follow the standard Answer Set Programming naming conventions when naming the atoms, constants and variables. The names of atoms and constants begin with a lowercase character, and variable names begin with an uppercase character.  If a symbol includes multiple words, then an underscore character '_' is used as a separator, according to the `snake_case` notation.

== Names of Cyberismo concepts in `field` predicates

Some Cyberismo concepts are used in `field` predicates of generated logic programs. These names are given in `camelCase`, as following.

.Cyberismo concepts in `field` predicates
[%autowidth]
|===
|Concept  |Name in `field` predicates

|Card type
|`cardType`
|Last modified
|`lastModified`
|Title
|`title`
|Workflow state
|`workflowState`

|===
