== Introduction

A graph view defines a concrete view to a xref:docs_wp769ee4.adoc[graph model]. Views can even be defined in different modules from the original models, so you can use a graph model from a content module in your Cyberismo project with a custom view that you have defined. 

== Prerequisites

Before defining a graph view, you must define a graph model, or use an existing graph model.

== Managing graph views using the Cyberismo command line tool

To see a list of the available graph views, use the following command:

  $ cyberismo show graphViews

To see the help for how to create a graph view, use the following command:

  $ cyberismo create graphView --help

To create a new graph view, for example `myGraphView`, use the following command:

  $ cyberismo create graphView myGraphView

Cyberismo will create the following files:

* Graph view metadata file `.cards/local/graphView/myGraphView.json`
* Directory `.cards/local/graphViews/myGraphView/`
* View file `.cards/local/graphView/myGraphView/view.lp.hbs`

If the card prefix of your Cyberismo project is `example`, then the full name of the new graph view will be `example/graphViews/myGraphView`.

When choosing a name for your graph view, see xref:docs_8.adoc[Naming conventions].

To finalise the graph view definition, you need to use a text editor to 

* Edit the basic graph view metadata in the `.cards/local/graphViews/myGraphView.json` file 
* If your graph view takes additional parameters, edit the graph view parameters schema files in `.cards/local/graphViews/parameterSchema.json`
* Edit the view implementation in `.cards/local/graphViews/myGraphView/view.lp.hbs`

== Graph view JSON file format

Basic metadata for a graph view is defined in a JSON file that follows the https://github.com/CyberismoCom/cyberismo/blob/main/tools/assets/src/schema/resources/graphViewSchema.json[graph view schema], as described in the following table.

.The properties of a graph view JSON file
|===
|Properties|Type|Description|Required

|**name**
|`string`
|The technical name of the graph view
| &#10003; Yes

|**displayName**
|`string`
|The name of the graph view as it should be displayed in the user interface. For example, 'Workflow'.
| &#10003; Yes

|**description**
|`string`
|A description of the graph view. For example, "A diagram of the state machine of a workflow".
| No

|**category**
|`string`
| The category of the graph model. For example, 'General'.
| &#10003; Yes

|===

Additional properties are not allowed.

== Graph macro parameter schema

The parameter schema file `parameterSchema.json` defines a https://json-schema.org/[JSON schema] for the graph macro parameters.

NOTE: If your graph view does not require custom parameters to the graph macro, then you can leave this file as it is by default. You only need to edit this file, if your graph view takes additional parameters.

The graph macro that can be included in card contents has the following format. In this case, the `workflow` parameter is an additional, graph-specific parameter.

```
{{#raw}}

{{#graph}}

    "model": "base/graphModels/workflow",
    "view": "base/graphViews/workflow", 
    "workflow": "base/workflows/page"
{{/graph}}

{{/raw}}

```

The parameters that are enclosed within the graph macro form technically a JSON object, even though the leading `{` and trailing `}` characters have been omitted for improved readability. Cyberismo validates the parameters of the graph macro using JSON schema validation.

The card key of the card in which the macro was included is always included in `cardKey` property of the parameters object. The user can override this by setting a `cardKey` property to some other card key.

Sometimes, it is useful to define additional parameters for a graph view. In the example above, the workflow graph is rendered only for the given workflow. In these cases, you need to edit the `parameterSchema.json` file and add a definition of your additional parameters. 

For example, the following `parameterSchema.json` file defines the parameters for a graph view that requires the `workflow` parameter to contain a string. The `model`, `view`, and `cardKey` parameters are included in the parameterSchema.json file by default:

----
{
  "title": "Graph view",
  "$id": "workflowGraphViewSchema",
  "description": "Parameters for the workflow graph view",
  "type": "object",
  "properties": {
    "model": {
      "description": "The name of the graph model",
      "type": "string"
    },
    "view": {
      "description": "The name of the graph view",
      "type": "string"
    },
    "cardKey": {
      "description": "Used to override the default cardKey, which is the cardKey of the card, in which the report macro is used",
      "type": "string"
    },
    "workflow": {
      "description": "The name of the workflow for which a graph will be generated",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": ["model", "view", "workflow"]
----


== Graph view implementation

The graph view implementation is a Handlebars template for a logic program. When a graph macro is rendered, Cyberismo will first run Handlebars on the graph view, using the parameters of the graph macro as the Handlebars context. This allows the view to be customised, for example, based on the card that included the graph macro, or based on parameters that were given to the graph macro. 

After running Handlebars on the view, Cyberismo will combine the graph model and the graph view with the global Cyberismo logic program to produce a Clingraph-like description of a graph based on your data.

There is no strict rule for what a graph view implementation should include, but this depends on how the model has been implemented.


== Mapping to a logic program

Cyberismo does not currently generate logic program facts for graph views.

