== Podman image from Docker Hub

=== Disclaimer

The Podman environment has been verified to work with Cyberismo Docker Hub images; however, it is not actively tested or maintained. Therefore, we cannot guarantee full compatibility or functionality.

=== Prerequisites

Install Git. While Cyberismo does not directly depend on Git, you will need it to manage Cyberismo content, such as when installing Cyberismo modules. Git installation guide: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

The system must have Podman or a similar container environment installed, capable of running Linux-based images. The simplest way to install a container environment is to install https://podman.io/docs/installation[Podman installation]

=== Downloading image from Docker Hub
The latest image can be downloaded with the following command:

  $ podman pull docker.io/cyberismo/cyberismo

=== Running

*Linux & macOS*

To simplify running the image, you can use the following alias:

  $ alias cyberismo='podman run --init --rm -it --userns=keep-id -e HOME=/tmp -v $(pwd):/project:Z -p 127.0.0.1:3000:3000 docker.io/cyberismo/cyberismo:latest cyberismo'

.Explanation of alias
[%collapsible]
====
The alias command allows you to execute the configured Podman environment with a single, simple command.

Flags in command:

* --init flag ensures proper signal handling and zombie process reaping in the container.
* -rm: Removes the container automatically after it exits.
* -it: Runs the container in interactive mode.
* --userns: Container user will use the same user id as the user executing the command. This will prevent file ownership problems.
* -e HOME=/some/path sets the HOME environment variable so tools like Antora can write to user-specific directories without permission errors.
* -v: Maps the current execution directory to the /project directory inside the container, sharing files between host and container.
* to support *Security-Enhanced Linux (SELinux)*, the volume mount includes the :Z option and uses an absolute path to the present working directory (`-v $(pwd):/project:Z`) 
* -p: Forwards the port from the container to the host machine, enabling access to the hosted web service.
====

Afterward, you can run the application using the following command:

  $ cyberismo --help

*Windows*

The Windows environment does not support aliases like Linux and macOS do, so the command to use Podman is:

  $ podman run --rm -it --userns=keep-id -v .:/project -p 127.0.0.1:3000:3000 docker.io/cyberismo/cyberismo cyberismo --help



