== Building and running Cyberismo from source

=== Prerequisites

. Install Git. While Cyberismo does not directly depend on Git, you will need it to manage Cyberismo content, such as when installing Cyberismo modules.

. Install Clingo. The currently supported Clingo version is 5.7.1. We recommend installing a Python-enabled build using Anaconda, as instructed in https://github.com/potassco/clingo/releases/.

. Install Node.js. The currently supported Node.js version is the latest LTS, v20.10.0. Node.js is downloadable from https://nodejs.org/.


=== Building

Take the following steps:

. Clone the source repository using one of the following methods:

  $ git clone git@github.com:CyberismoCom/cyberismo.git # SSH
  $ git clone https://github.com/CyberismoCom/cyberismo.git # HTTPS
  
. Change to the source directory. If you have already cloned the repository earlier, remember to pull the latest changes:

  $ cd cyberismo
  $ git pull origin main # Optional
  
. Execute the following commands:

  $ pnpm setup
  $ pnpm install
  $ pnpm build
  $ pnpm link -g

=== Running

After building and installing, run `cyberismo --help` to see the command line help.