== Method 1: Docker image from Docker Hub

This method is likely to be the simplest way to get started with Cyberismo.

=== Prerequisites
. Install Git. While Cyberismo does not directly depend on Git, you will need it to manage Cyberismo content, such as when installing Cyberismo modules.

. The system must have Docker or a similar container environment installed, capable of running Linux-based images. The simplest way to install a container environment is to install https://www.docker.com[Docker Desktop].

=== Downloading image from Docker Hub
The latest image can be downloaded with the following command:

  $ docker pull cyberismo/cyberismo

Specific versions can be downloaded with the following command:

  $ docker pull cyberismo/cyberismo:0.1

=== Running
* It is recommended to execute the following commands only within the Cyberismo root directory or within project directories.

* To simplify running the image, you can use the following command (works only on Unix-based systems, not in CMD or PowerShell):

  $ alias cyberismod="docker run --rm -it --user $(id -u):$(id -g) -v .:/project -p 3000:3000 cyberismo/cyberismo cyberismo"

The alias command allows you to execute the configured Docker environment with a single, simple command.

* Flags in command:
** -rm: Removes the container automatically after it exits.
** -it: Runs the container in interactive mode.
** --user: Container user will use the same user id as the user executing the command. This will prevent file ownership problems.
** -v: Maps the current execution directory to the /project directory inside the container, sharing files between host and container.
** -p: Forwards the port from the container to the host machine, enabling access to the hosted web service.

* Run the following command to view the command-line help:

  $ cyberismod --help

NOTE: The rest of the Cyberismo documentation uses the name `cyberismo` for the Cyberismo command. If you have installed Cyberismo using Docker as instructed here, then you need to use the alias command `cyberismod` instead of `cyberismo`.

== Method 2: Locally built Docker image

=== Prerequisites
. Install Git. While Cyberismo does not directly depend on Git, you will need it to manage Cyberismo content, such as when installing Cyberismo modules.

. The system must have Docker or a similar container environment installed, capable of running Linux-based images. The simplest way to install a container environment is to install https://www.docker.com[Docker Desktop].

=== Building the container image
Take the following steps:

. Clone the source repository using one of the following methods:

  $ git clone git@github.com:CyberismoCom/cyberismo.git # SSH
  $ git clone https://github.com/CyberismoCom/cyberismo.git # HTTPS
  
. Change to the source directory. If you have already cloned the repository earlier, remember to pull the latest changes:

  $ cd cyberismo
  $ git pull origin main # Optional

. Execure the following commands:

  $ docker build -t cyberismo .

. Once the build has finished, you can verify the existence of the built image with the following command:

  $ docker images

=== Running
* It is recommended to execute the following commands only within the Cyberismo root directory or within project directories.

* To simplify running the image, you can use the following command (works only on Unix-based systems, not in CMD or PowerShell):

  $ alias cyberismod="docker run --rm -it --user $(id -u):$(id -g) -v .:/project -p 3000:3000 cyberismo cyberismo"

The alias command allows you to execute the configured Docker environment with a single, simple command.

* Flags in command:
** -rm: Removes the container automatically after it exits.
** -it: Runs the container in interactive mode.
** --user: Container user will use the same user id as the user executing the command. This will prevent file ownership problems.
** -v: Maps the current execution directory to the /project directory inside the container, sharing files between host and container.
** -p: Forwards the port from the container to the host machine, enabling access to the hosted web service.

* Run the following command to view the command-line help:

  $ cyberismod --help

NOTE: The rest of the Cyberismo documentation uses the name `cyberismo` for the Cyberismo command. If you have installed Cyberismo using Docker as instructed here, then you need to use the alias command `cyberismod` instead of `cyberismo`.

== Method 3: Building and running Cyberismo locally from source

=== Prerequisites

. Install Git. While Cyberismo does not directly depend on Git, you will need it to manage Cyberismo content, such as when installing Cyberismo modules.

. Install Clingo. The currently supported Clingo version is 5.7.1. We recommend installing a Python-enabled build using Anaconda, as instructed in https://github.com/potassco/clingo/releases/.

. Install Node.js. The currently supported Node.js version is the latest LTS, v20.10.0. Node.js is downloadable from https://nodejs.org/.

. Install the latest version of https://antora.org/[Antora].

. Install the latest version of https://clingraph.readthedocs.io/en/latest/clingraph/installation.html[Clingraph].


=== Building

Take the following steps:

. Clone the source repository using one of the following methods:

  $ git clone git@github.com:CyberismoCom/cyberismo.git # SSH
  $ git clone https://github.com/CyberismoCom/cyberismo.git # HTTPS
  
. Change to the source directory. If you have already cloned the repository earlier, remember to pull the latest changes:

  $ cd cyberismo
  $ git pull origin main # Optional
  
. Execute the following commands:

  $ pnpm setup
  $ pnpm install
  $ pnpm build
  $ pnpm link -g

=== Running

After building and installing, run `cyberismo --help` to see the command line help.