This page describes the fields of the cards in the Cyberismo content format. For custom fields, the format uses a separate concept of a field type.

== Common card metadata fields

The following table documents the common metadata that can be included for any card regardless of the card type.

.Common metadata fields of cards
|===
|Property|Type|Description|Required

|**cardType**
|`string`
|The name of the card type
| &#10003; Yes

|**title**
|`string`
|A short title of the card
| &#10003; Yes

|**workflowState**
|`string`
|the name of the card's current state in the workflow
| &#10003; Yes

|**labels**
|`string` `[]`
|Labels or tags that can be used for organising cards
|No

|**links**
|`object` `[]`
|links to or from this card to other cards
|No

|===

To enable card type specific custom fields, additional properties are allowed. The custom fields are card metadata properties, whose name is a name of a field type.

== Custom fields

Custom fields are defined in separate field type definitions. The properties of a field type are described in the following table.

.Properties of a field type
|===
|Property|Type|Description|Required

|**name**
|`string`
|The technical name by which the field is referred to.
| &#10003; Yes

|**displayName**
|`string`
|A name by which the field is referred to in the user interface.
|No

|**fieldDescription**
|`string`
|A longer description of the field type.
|No

|**dataType**
|`string`
|The data type of the field.
| &#10003; Yes

|**enumValues**
|`object` `[]`
|An array of available enum values. Used for the enum and list data types only.
|No

|===

=== Data types of custom fields

The data type of a custom field must be one of the following values:

* **`shorttext`**: A string that contains a single line of text.
* **`longtext`**: A string that contains a longer text that may have multiple lines.
* **`number`**: A number that may be a floating point number or an integer (a standard JSON type).
* **`integer`**: An integral number (a standard JSON type).
* **`boolean`**: Either true or false (a standard JSON type). In user interfaces, boolean values may be presented by display names Yes and No.
* **`enum`**: An enumeration. A string that has one of the values defined in a separate `enumValues` array. In user interfaces, an enum is represented as a selection component (drop down list).
* **`list`**: An array that contains zero or more strings, where the allowed values are defined in a separate `enumValues` array. In user interfaces, a list data type is represented as a multiple selection component, where the user can select zero or more of the available options.
* **`date`**: A string that represents a date in the ISO 8601 format. For example "2024-01-01".
* **`datetime`**: A string that represents date and time in UTC in the ISO 8601 format. For example "2024-06-09T08:43:25Z".
* **`person`**: A string that is an email address of a person.
* **`persons`**: an array of strings, where each string is an email address of a person.
* **`strings`**: an array of arbitrary strings.

===  Enum values of a field type

The `enumValues` property of a field type is an array of available values in selection data types. This property is used for the enum and list data types only. The items of the array are objects that have the following properties:

.Properties of the items in the enumValues array
|===
|Property|Type|Description|Required

|**enumValue**
|`string`
|A string that represents a possible value for an enum field or for an item in a list array.
| &#10003; Yes

|**enumDisplayValue**
|`string`
|A display name for the enum value for user interfaces.
| No

|**enumDescription**
|`string`
|A longer description of the enum value.
| No

|===

