name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - deploy/static
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - deploy/static

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build docs and deploy to Azure
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout cyberismo-docs repository
        uses: actions/checkout@v4
        with:
          repository: CyberismoCom/cyberismo-docs
          path: cyberismo-docs

      - name: Clone cyberismo repository
        uses: actions/checkout@v4
        with:
          repository: CyberismoCom/cyberismo
          path: cyberismo
          ref: main

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          auto-update-conda: true
          activate-environment: docs-env
          environment-file: cyberismo-docs/environment.yml

      - name: Check Clingo Availability
        run: which clingo

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install the Cyberismo application
        run: |
          cd cyberismo
          pnpm install
          pnpm build
          pnpm link -g

      - name: Export the site
        run: |
          cyberismo export site -p cyberismo-docs build/site
          touch build/site/.nojekyll
          find build/site

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_BUSH_067DD8C03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build/site" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_BUSH_067DD8C03 }}
          action: "close"
          app_location: "/"
