name: Build and Export Cyberismo Site

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
  
    permissions:
      contents: read
      packages: write
  
    steps:
    - name: Checkout cyberismo-docs repository
      uses: actions/checkout@v4
      with:
        repository: CyberismoCom/cyberismo-docs

    - name: Clone cyberismo repository
      uses: actions/checkout@v4
      with:
        repository: CyberismoCom/cyberismo
        path: cyberismo

    - name: Install dependencies
      run: |
        cd cyberismo
        npm install

    - name: Build project
      run: |
        cd cyberismo
        npm run build

    - name: Install globally
      run: |
        cd cyberismo
        npm install -g

    - name: Export site
      run: |
        cd cyberismo
        cyberismo export site /tmp/site
