name: Build and Export Cyberismo Site

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
  
    permissions:
      contents: read
      packages: write
  
    steps:
    - name: Checkout cyberismo-docs repository
      uses: actions/checkout@v4
      with:
        repository: CyberismoCom/cyberismo-docs
        path: cyberismo-docs

    - name: Clone cyberismo repository
      uses: actions/checkout@v4
      with:
        repository: CyberismoCom/cyberismo
        path: cyberismo

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        find cyberismo-docs

    - name: Install dependencies
      run: |
        cd cyberismo
        npm install
        npm run build
        npm install -g

    - name: Export site
      run: |
        cd cyberismo-docs
        cyberismo export site /tmp/site
